# Generated by Django 3.0 on 2020-01-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('market_cap', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Market Cap')),
                ('p_b', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='P/B')),
                ('last_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Last Price')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitsToAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='year')),
                ('profitability', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Profitability')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investing.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Profitability')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock')),
            ],
        ),
    ]
