# Generated by Django 3.0 on 2020-01-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0002_remove_stock_last_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Market Cap'),
        ),
    ]
