# Generated by Django 3.0 on 2020-01-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0003_auto_20200121_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='yahoo_ticker',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
