# Generated by Django 3.0 on 2020-01-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0005_stock_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
