# Generated by Django 3.0 on 2020-02-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0008_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Date'),
        ),
    ]
