# Generated by Django 3.0 on 2020-02-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0009_auto_20200202_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
