# Generated by Django 3.0 on 2020-02-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0011_auto_20200202_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGA_Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='year')),
                ('SGA_Expense', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='SGA_Expense')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investing.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='year')),
                ('revenue', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Revenue')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investing.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='year')),
                ('liabilities', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Liabilities')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investing.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='InterestExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='year')),
                ('interestExpense', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='InterestExpense')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investing.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='CoGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='year')),
                ('CoGS', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='CoGS')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investing.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='year')),
                ('assets', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Assets')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investing.Stock')),
            ],
        ),
    ]
