# Generated by Django 3.0 on 2020-02-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0012_assets_cogs_interestexpense_liabilities_revenue_sga_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingProfitability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='year')),
                ('OP', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='OP')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investing.Stock')),
            ],
        ),
    ]
