# Generated by Django 3.0 on 2020-02-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0014_marketcap_marketcapindollars_pricetobook_sharesoutstanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='year')),
                ('investment', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Investment')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investing.Stock')),
            ],
        ),
    ]
