# Generated by Django 3.0 on 2020-02-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0016_auto_20200210_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='interestexpense',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='marketcap',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='marketcapindollars',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='operatingprofitability',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='pricetobook',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='profitstoassets',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='sga_expense',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AlterField(
            model_name='sharesoutstanding',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
    ]
